// Regenerates src/components/iconify.js with embedded (offline) SVG data for the
// item icons, fetched from https://iconify.design.
// Usage:  node scripts/fetch-iconify.js
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

// Iconify name → the mockData item icon value must match these keys.
const ICONS = [
  'material-symbols:laundry-outline',
  'tabler:shirt',
  'boxicons:t-shirt',
  'dinkie-icons:jeans',
  'hugeicons:kurta',
  'ph:dress',
  'mingcute:trouser-line',
  'hugeicons:suit-02',
  'mingcute:coat-line',
  'fluent:premium-20-filled',
  'boxicons:sneaker',
  'maki:shoe',
  'hugeicons:sandals',
  'lucide:handbag',
  'material-symbols:backpack-outline-rounded',
  'fluent:backpack-add-28-regular',
  'griddy-icons:blanket',
  'mingcute:curtain-line',
  'mdi:carpet',
  // Support section
  'material-symbols:support-agent-rounded',
  'ic:baseline-whatsapp',
]

const here = dirname(fileURLToPath(import.meta.url))
const out = join(here, '..', 'src', 'components', 'iconify.js')

const icons = {}
for (const key of ICONS) {
  const res = await fetch(`https://api.iconify.design/${key}.svg`)
  if (!res.ok) throw new Error(`fetch failed (${res.status}): ${key}`)
  const svg = await res.text()
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] || '0 0 24 24'
  const inner = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()
  icons[key] = {
    viewBox,
    // Stroke-based icon sets (tabler, hugeicons, mingcute, lucide) draw with
    // stroke="currentColor"; fill-based sets (material-symbols, fluent, mdi,
    // boxicons, phosphor, dinkie, maki, griddy) fill with currentColor.
    mode: inner.includes('stroke=') ? 'stroke' : 'fill',
    svg: inner,
  }
}

const body =
  '// Iconify icon data, embedded for offline use.\n' +
  '// Generated by scripts/fetch-iconify.js — do not edit by hand.\n' +
  'export const ICONIFY = ' +
  JSON.stringify(icons, null, 2) +
  '\n'
writeFileSync(out, body)
console.log(`wrote ${Object.keys(icons).length} icons to ${out}`)
